circuits = [
    'Albert Park Grand Prix Circuit',
    'Autódromo José Carlos Pace',
    'Autodromo Nazionale di Monza',
    'Autódromo Hermanos Rodríguez',
    'Autódromo Internacional do Algarve',
    'Autódromo José Carlos Pace',
    'Bahrain International Circuit',
    'Baku City Circuit',
    'Circuit de Barcelona-Catalunya',
    'Circuit de Monaco',
    'Circuit de Spa-Francorchamps',
    'Circuit Gilles Villeneuve',
    'Circuit of the Americas',
    'Circuit Park Zandvoort',
    'Circuit Paul Ricard',
    'Hockenheimring',
    'Hungaroring',
    'Istanbul Park',
    'Jeddah Corniche Circuit',
    'Losail International Circuit',
    'Marina Bay Street Circuit',
    'Miami International Autodrome',
    'Nürburgring',
    'Red Bull Ring',
    'Sepang International Circuit',
    'Shanghai International Circuit',
    'Silverstone Circuit',
    'Sochi Autodrom',
    'Suzuka Circuit',
    'Yas Marina Circuit',
]

seasons = [
    2014,
    2015,
    2016,
    2017,
    2018,
    2019,
    2020,
    2021,
    2022,
]